version: '3'
services:
  liblaas:
    depends_on: 
      - db
    volumes:
      - config_data:/usr/src/liblaas/config_data
    networks:
      - laasctl_network
    ports:
      - target: 3001
        published: 3001
        protocol: tcp
        mode: host

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "{POSTGRES_PASSWORD:-password}"
      POSTGRES_DB: "${POSTGRES_DB:-liblaas}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laasctl_network

volumes:
  pgdata:
  config_data:
networks:
  laasctl_network:
    name: laasctl_network
    external: true
