version: "3"
services:
  liblaas:
    build: .
    depends_on:
      - db
    networks:
      - laasctl_network
    ports:
      - "${LAAS_MAILBOX_PORT}:${LAAS_MAILBOX_PORT}"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "{POSTGRES_PASSWORD:-password}"
      POSTGRES_DB: "${POSTGRES_DB:-liblaas}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laasctl_network
volumes:
  pgdata:
  config_data:
networks:
  laasctl_network:
    name: laasctl_network
    external: true
