[[servers]]
host = "$__env{LDAP_HOST}"
port = 636
use_ssl = true
start_tls = false
ssl_skip_verify = false
root_ca_cert = "/etc/ssl/certs/ca.crt"
bind_dn = "$__env{LDAP_BIND_DN}"
bind_password = "$__env{LDAP_BIND_PASSWORD}"
timeout = 10
search_filter = "(uid=%s)"
search_base_dns = ["cn=users,cn=accounts,dc=os,dc=iol,dc=unh,dc=edu"]

[servers.attributes]
member_of = "memberOf"
email = "email"
name = "givenName"
surname = "sn"
username = "uid"

[[servers.group_mappings]]
group_dn = "cn=admin,cn=groups,cn=accounts,dc=os,dc=iol,dc=unh,dc=edu"
org_role = "Admin"

[[servers.group_mappings]]
group_dn = "cn=iol-team,cn=groups,cn=accounts,dc=os,dc=iol,dc=unh,dc=edu"
org_role = "Editor"

[[servers.group_mappings]]
group_dn = "*"
org_role = "Viewer"
