[package]
name = "dal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }
serde_with = { workspace = true }
derive_more = { workspace = true }
uuid = { workspace = true }
sha2 = { workspace = true }
base16ct = { workspace = true }
inventory = { workspace = true }
backtrace = { workspace = true }

common = { path = "../common" }
